# Generated by Django 4.1.7 on 2023-02-28 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investor',
            options={'ordering': ['last_name']},
        ),
        migrations.AddField(
            model_name='investor',
            name='fund',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='funds.fund'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investor',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
